# Generated by Django 3.2.23 on 2024-05-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
        ('Company_Staff', '0004_auto_20240503_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashInHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment', models.CharField(choices=[('Reduce Cash', 'Reduce Cash'), ('Add Cash', 'Add Cash')], max_length=50)),
                ('amount', models.BigIntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
            ],
        ),
    ]
